#!/bin/sh

CMD="paver -server -role admin -role master -role root"

tb() {
	eae-telegram-bot "Paver Check. FAILED: $1" >/dev/null
}

request() {
	curl --silent --fail --location $@ >/dev/null || return 1
}

if ! pgrep -xf "$CMD" >/dev/null; then
	tb "Paver not running. Trying to restart it..."
	$CMD
	exit 1
fi

if ! request --unix-socket /tmp/paver-server.sock http://localhost/; then
	tb "Socket Error"
	exit 1
fi

if ! request https://admin.energyaccessexplorer.org/paver/check; then
	tb "Fetching production failed"
	exit 1
fi
