#!/bin/sh

SOCKET="/tmp/paver-server.sock"

tb() {
	eae-telegram-bot "Paver Check. FAILED: $1" >/dev/null
}

request() {
	curl --silent --fail --location $@ >/dev/null || return 1
}

if ! pgrep -f "paver -server" >/dev/null; then
	tb "Paver not running. Trying to restart it..."
	sudo systemct restart paver.service
	exit 1
fi

if ! request --unix-socket $SOCKET http://localhost/check; then
	tb "Socket Error"
	exit 1
fi

if ! request https://admin.energyaccessexplorer.org/paver/check; then
	tb "Fetching production failed"
	exit 1
fi
